[package]
name = "minecraft-lan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-net = "1.5"
regex = "1.7.2"
socket2 = { version = "0.3", features = ["reuseport"] }
